# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-dfplayer-project"
BBFILE_PATTERN_meta-dfplayer-project = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-dfplayer-project = "6"

LAYERDEPENDS_meta-dfplayer-project = "core"
LAYERSERIES_COMPAT_meta-dfplayer-project = "scarthgap"
